sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      env:
        - CODECOVERAGE=1
    - php: 7.2
      env:
        - PHPCS=1

before_script: .travis/before-script.sh
script: .travis/script.sh
after_success: .travis/after-success.sh

notifications:
  email: false
  slack:
    rooms:
      secure: "GKJEIVB0VV/H0ldrTWK9PHTzWgh9sCTan3UNwHVzXqNaLI8cA6qB5y2ap2iNzurrPyQ1mZUHYtGMMFjwhp7PsB4db1x6xtjpfKzWiL+EsQDnLMx/zJgx0MVbmE1+7gBYgFNRVgZDyFSL9wRj5G0mXowpa0NSS5P5UHVVbYxzCgM+RBiwqVQr+jBXH55rOLqWS+RwleX32e2rEjJP9Z3oHAaVCB7BXoSiybm02xAWq2wurbSTN0EAqpMDuXR4M+9wQrdYDV7PFyJ4yUUXj5riEOKmN77ztk+WvqVYUm8vlQOdV7THw/bv7Nm+Oej8MSIcatAMwiaqNfs0eAaZhEmiU8mZgr7MyS4iQsDdK7R//DdYjmAIPoefH7xDupe1ZiQPupUN6o2X1YIp7B1gMM0+ZzQUlqfSY6ZHVldAokUCrmHlwbDZJ61ESley6hnk+WO3fBdXa4Mp77CNBtszlSbgdzJhe6uDEf+466AsNZcy59YKsTQKk5TxjMg89kOHmSxnP/lWdyC7pibARLVySQZkitCra38pNNE2N9rUvTRICW/G589PsDdCA3LnYmV9tvFDeks4EuISWl1657TZWMC3ErnlT22YbHrxsXaFS/B30iPNY4+oruIMMjNITUNNjyefYMTIFLTPz7Tfrtufm0+wLkzEsuaaTJ4U1wadS+L+aLo="
