sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  include:
    - php: 7.2
      env:
        - CODECOVERAGE=1
    - php: 7.2
      env:
        - PHPCS=1

before_script: .travis/before-script.sh
script: .travis/script.sh
after_success: .travis/after-success.sh

notifications:
  email: false
